server:
  port: 8080

spring.datasource:
  driverClassName: "org.postgresql.Driver"
  url : "jdbc:postgresql://localhost:5432/bc2412"
  username: "postgres"
  password: "Lamz999*"

spring.jpa:
  show-sql: true
  hibernate.ddl-auto: update

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
