server:
  port: 8099

api:
  yahooFinance:
    host: "query1.finance.yahoo.com"
    endpoints:
      data: "/v7/finance/quote"
      key: "/v1/test/getcrumb"
      
spring.datasource:
  driverClassName: "org.postgresql.Driver"
  url : "jdbc:postgresql://localhost:5432/stockfinance"
  username: "postgres"
  password: "Lamz999*"

spring.jpa:
  show-sql: true
  hibernate.ddl-auto: update